"""Add indexes to Package model

Revision ID: 940380ab1998
Revises: 
Create Date: 2025-10-22 15:56:01.961324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940380ab1998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_title'))
        batch_op.drop_index(batch_op.f('ix_package_price'))
        batch_op.drop_index(batch_op.f('ix_package_duration'))
        batch_op.drop_index(batch_op.f('ix_package_destination'))

    # ### end Alembic commands ###
