"""Add gallery_images column to Package model

Revision ID: 1c61ba0e1f61
Revises: 80db9e716278
Create Date: 2025-10-26 20:47:22.334095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c61ba0e1f61'
down_revision = '80db9e716278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery_images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('itinerary_days', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('highlights', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('accommodation_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transportation_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_policy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('terms_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('map_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('map_location')
        batch_op.drop_column('video_url')
        batch_op.drop_column('terms_conditions')
        batch_op.drop_column('cancellation_policy')
        batch_op.drop_column('transportation_details')
        batch_op.drop_column('accommodation_details')
        batch_op.drop_column('highlights')
        batch_op.drop_column('itinerary_days')
        batch_op.drop_column('gallery_images')

    # ### end Alembic commands ###
